@startuml arcgis-web-service-sequence-diagram
participant WildlifeMortalities
participant Posse
participant ArcGISWebService

WildlifeMortalities -> Posse: Based on the applicable permit, sends a request asking for the arcgis URL
Posse -> WildlifeMortalities: Responds with URL
WildlifeMortalities -> ArcGISWebService: Sends request containing location and date of kill
ArcGISWebService -> ArcGISWebService: Determines if location is within the legal hunting boundary at that date
ArcGISWebService -> WildlifeMortalities: Responds with whether the location is within the boundary

@enduml