@startuml goal-process
!theme materia
skinparam backgroundColor white
title goal process (stage 1, detailed)

actor "Client" as client
actor "FOA/CO" as foa
participant "Wildlife Mortalities" as wm
actor "F&W" as fw
loop
    foa -> client : request information
    client --> foa : provide information
    foa -> wm : enter data
end

    loop
        foa -> wm : submit report
        wm -> wm : validate data
        alt validation success
            wm -> wm: accept report and exit loop
        else validation failure
            wm --> foa: reject report
            alt error by FOA
                foa -> foa : fix error
            else error by client
                foa -> client : request corrected information
                client --> foa : provide corrected information
                foa -> foa : fix error
        end
    end
end
wm -> wm : analyze report and generate violations
wm -> foa : display submitted report
alt report has violation(s)
    foa -> client : inform client of violation(s)
    alt violation caused by data entry error
        foa -> wm : edit and submit report
    else violation is valid
    end
else report has no violation
end
foa -> wm : request report PDF
wm -> wm : generate PDF
wm --> foa : provide PDF
foa -> foa : print PDF
foa -> client : provide printed report
foa -> client : thank client
client -> client: leave
fw -> wm : view report