@startuml logical-erd
'!theme spacelab
title Logical ERD

' avoid problems with angled crows feet
skinparam linetype ortho

' Entities

together {

    entity "HarvestReport" as harvest_report {
        *Id: number <<generated>>
        --
        *DateStarted: datetime
        *DateCompleted: datetime
        *IsComplete: bool
    }
    entity "HuntedHarvestReport" as hunted_harvest_report {
        GameManagementAreaSpeciesId: number <<FK>>
        SealId: number <<FK>>
    }
    entity "TrappedHarvestReport" as trapped_harvest_report {

    }
}

together {
    entity "Mortality" as mortality {
        *Id: number <<generated>>
        --
        *ReporterId: number <<FK>>
        *Sex: enum
        Latitude: number
        Longitude: number
    }
    entity "BirdMortality" as bird_mortality {
        BirdSpecies: enum
    }
    entity "BisonMortality" as bison_mortality {
        HarvestReportId: number <<FK>>
        Landmark: string
    }
    entity "BlackBearMortality" as black_bear_mortality {
        HarvestReportId: number <<FK>>
        Landmark: string
    }
    entity "CaribouMortality" as caribou_mortality {
        HarvestReportId: number <<FK>>
        Landmark: string
    }
    entity "CoyoteMortality" as coyote_mortality {
        HarvestReportId: number <<FK>>
        Landmark: string
    }
    entity "DeerMortality" as deer_mortality {
        HarvestReportId: number <<FK>>
        Landmark: string
    }
    entity "ElkMortality" as elk_mortality {
        HarvestReportId: number <<FK>>
        Landmark: string
    }
    entity "GoatMortality" as goat_mortality {
        HarvestReportId: number <<FK>>
        Landmark: string
    }
    entity "GrizzlyBearMortality" as grizzly_bear_mortality {
        HarvestReportId: number <<FK>>
        Landmark: string
    }
    entity "MooseMortality" as moose_mortality {
        HarvestReportId: number <<FK>>
        Landmark: string
    }
    entity "SheepMortality" as sheep_mortality {
        HarvestReportId: number <<FK>>
        Landmark: string
    }
    entity "WolfMortality" as wolf_mortality {
        HarvestReportId: number <<FK>>
        Landmark: string
        *HarvestType: enum
    }
    entity "WolverineMortality" as wolverine_mortality {
        HarvestReportId: number <<FK>>
        Landmark: string
        *HarvestType: enum
    }
}

entity "BiologicalSubmission" as biological_submission {
    *Id: number <<generated>>
    --
    *MortalityId: number <<FK>>
}

together {
    entity "Reporter" as reporter {
        *Id: number <<generated>>
    }

    entity "ConservationOfficer" as conservation_officer {
        *BadgeNumber: string
    }

    together {
        entity "Client" as client {
            *EnvClientId: string
        }

        entity "Licence" as licence {
            *Id: number <<generated>>
            --
            *ClientId: number <<FK>>
            *Number: string
            *LicenceType: enum
            *PosseId: number <<shadow>>
        }

        entity "Seal" as seal {
            *Id: number <<generated>>
            --
            *LicenceId: number <<FK>>
            *PosseId: number <<shadow>>
        }
    }
}

entity "GameManagementArea" as game_management_area {
    *Id: number <<generated>>
    --
    *Zone: string
    *Subzone: string
    Area: string <<computed>>
}

entity "GameManagementAreaSpecies" as game_management_area_species {
    *Id: number <<generated>>
    --
    *GameManagementAreaId: number <<FK>>
    *GmaSpecies: enum
}

entity "GameManagementAreaSchedule" as game_management_area_schedule {
    *Id: number <<generated>>
    --
    *GameManagementAreaSpeciesId: number <<FK>>
    *GmaStatus: enum
    *PeriodStart: date
    *PeriodEnd: date
}

entity "GameManagementUnit" as game_management_unit {
    *Id: number <<generated>>
    --
    *Name: string
    *Number: string
    *ActiveFrom: date
    *ActiveTo: date
}

' Inheritance

harvest_report <|-- hunted_harvest_report
harvest_report <|-- trapped_harvest_report

reporter <|-- client
reporter <|-- conservation_officer

mortality <|-- bird_mortality
mortality <|-- bison_mortality
mortality <|-- black_bear_mortality
mortality <|-- caribou_mortality
mortality <|-- coyote_mortality
mortality <|-- deer_mortality
mortality <|-- elk_mortality
mortality <|-- goat_mortality
mortality <|-- grizzly_bear_mortality
mortality <|-- moose_mortality
mortality <|-- sheep_mortality
mortality <|-- wolf_mortality
mortality <|-- wolverine_mortality

' Relationships

hunted_harvest_report }o..|| game_management_area_species
hunted_harvest_report |o..|| seal

mortality ||..o| biological_submission
mortality }o..|| reporter
mortality ||..o| hunted_harvest_report

client ||..o{ licence
licence ||..o{ seal

game_management_area ||..{ game_management_area_species
game_management_area_species ||..{ game_management_area_schedule
game_management_unit }..{ game_management_area_species

' Enums

enum "AllSpecies" as all_species {
    Uninitialized
    AmericanBeaver
    AmericanBlackBear
    AmericanMartin
    AmericanMink
    ArcticFox
    ArcticGroundSquirrel
    BarrenGroundCaribou
    BushyTailedWoodrat
    CanadaLynx
    CollaredPika
    Cougar
    Coyote
    Elk
    Ermine
    Fisher
    GreyWolf
    GrizzlyBear
    HoaryMarmot
    LeastChipmunk
    LeastWeasel
    Lemming
    LittleBrownBat
    MeadowJumpingMouse
    Moose
    MountainGoat
    MuleDeer
    Muskox
    Muskrat
    NorthAmericanDeerMouse
    NorthAmericanPorcupine
    NorthernFlyingSquirrel
    NorthernLongEaredBat
    NorthernRiverOtter
    PolarBear
    RedFox
    RedSquirrel
    Shrew
    SnowshoeHare
    ThinhornSheep
    Vole
    Wolverine
    WoodBison
    Woodchuck
    WoodlandCaribou
}

enum "BirdSpecies" as bird_species {

}

enum "HuntedSpecies" as hunted_species {
    Uninitialized
    AmericanBlackBear
    BarrenGroundCaribou
    Coyote
    Elk
    GreyWolf
    GrizzlyBear
    Moose
    MountainGoat
    MuleDeer
    ThinhornSheep
    Wolverine
    WoodBison
    WoodlandCaribou
}

enum "HuntedSpeciesWithGameManagementArea" as hunted_species_with_gma {
    Uninitialized
    AmericanBlackBear
    BarrenGroundCaribou
    GrizzlyBear
    Moose
    MountainGoat
    MuleDeer
    ThinhornSheep
    WoodBison
    WoodlandCaribou
}

enum "TrappedSpecies" as trapped_species {
    Uninitialized
    GreyWolf
    Wolverine
}

enum "GameManagementAreaStatus" as gma_status {
    Uninitialized
    Closed
    Open
    OpenPermitRequired
}

enum "LicenceType" as licence_type {
    Uninitialized
    Hunting
    HuntingPermit
    HuntingPhaPermit
    SpecialGuide
    Trapping
}

enum "HarvestType" as harvest_type {
    Uninitialized

}

enum "Sex" as sex {
    Uninitialized
    Female
    Male
    Unknown
}
@enduml