@startuml logical-erd
title Logical ERD

skinparam linetype ortho
skinparam arrowThickness 1.5

' Entities
together {
    together {
        entity "MortalityReport" as mortality_report {
            *Id: number <<generated>>
            --
            
        }
        entity "HuntedMortalityReport" as hunted_mortality_report {
            *ClientId: number <<FK>>
            GameManagementAreaSpeciesId: number <<FK>>
            SealId: number <<FK>>
            *DateStarted: date
            *DateCompleted: date
            *Landmark: string
            *HuntedHarvestReportStatus: enum
        }
        /' entity "TrappedHarvestReport" as trapped_harvest_report {
            *Id: number <<generated>>
            --
            LicenceId: number <<FK>>
        } '/
        entity "HumanWildlifeConflictMortalityReport" as human_wildlife_conflict_report {
            *ConservationOfficerId: number <<FK>>
            *HumanWildlifeConflictNumber: number
        }
        entity "CollaredMortalityReport" as collared_mortality_report {

        }
    }
    entity "OutfitterGuideReport" as outfitter_guide_report {
        *Id: number <<generated>>
        --
        *OutfittingArea: enum
    }
    entity "OutfitterGuideReport_HuntedHarvestReport" as outfitter_guide_report_hunted_mortality_report {
        *OutfitterGuideReportId: <<FK>>
        *HuntedHarvestReportId: <<FK>>
    }
    entity "OutfitterGuideReport_Client" as outfitter_guide_report_client {
        *OutfitterGuideReportId: <<FK>>
        *GuideId: <<FK>>
    }
    entity "SpecialGuideReport" as special_guide_report {
        *Id: number <<generated>>
        --
        GuideId: <<FK>>
    }
    entity "SpecialGuideReport_HuntedHarvestReport" as special_guide_report_hunted_mortality_report {
        *SpecialGuideReportId: <<FK>>
        *HuntedHarvestReportId: <<FK>>
    }
    
}

together {
    ' Some less important mortality types are not included in this diagram to keep it a manageable size
    entity "Mortality" as mortality {
        *Id: number <<generated>>
        --
        *MortalityReportId: number <<FK>>
        *Sex: enum
        Latitude: number
        Longitude: number
    }
    entity "AmericanBlackBearMortality" as americanblackbear_mortality {
        *IsShotInConflict: bool
    }
    entity "BarrenGroundCaribouMortality" as barrengroundcaribou_mortality {
        *BarrenGroundCaribouHerd: enum
    }
    entity "CanadaLynxMortality" as canadalynx_mortality {

    }
    entity "CougarMortality" as cougar_mortality {

    }
    entity "CoyoteMortality" as coyote_mortality {

    }
    entity "ElkMortality" as elk_mortality {

    }
    entity "GreyWolfMortality" as greywolf_mortality {

    }
    entity "GrizzlyBearMortality" as grizzlybear_mortality {
        *IsShotInConflict: bool
    }
    entity "MooseMortality" as moose_mortality {

    }
    entity "MountainGoatMortality" as mountaingoat_mortality {

    }
    entity "MuleDeerMortality" as muledeer_mortality {

    }
    entity "MuskoxMortality" as muskox_mortality {

    }
    entity "PolarBearMortality" as polarbear_mortality {

    }
    entity "ThinhornSheepMortality" as thinhornsheep_mortality {
        *BodyColour: enum
        *TailColour: enum
    }
    entity "WhiteTailedDeerMortality" as whitetaileddeer_mortality {

    }
    entity "WolverineMortality" as wolverine_mortality {

    }
    entity "WoodBisonMortality" as woodbison_mortality {
        *PregnancyStatus: enum
        *IsWounded: bool
    }
    entity "WoodlandCaribouMortality" as woodlandcaribou_mortality {
        *WoodlandCaribouHerd: enum
    }
    entity "BirdMortality" as bird_mortality {
        BirdSpecies: enum
    }
}

entity "BiologicalSubmission" as biological_submission {
    *Id: number <<generated>>
    --
    *MortalityId: number <<FK>>
}
entity "AmericanBlackBearBiologicalSubmission" as americanblackbearbiological_submission {
    *SkullCondition: string
    *SkullLength: number
    *SkullHeight: number
}
entity "CanadaLynxBiologicalSubmission" as canadalynxbiological_submission {
    *PeltLength: number
    *PeltWidth: number
}
entity "ElkBiologicalSubmission" as elkbiological_submission {
    *IsHornIncluded: bool
    *IsHeadIncluded: bool
}
entity "GreyWolfBiologicalSubmission" as greywolfbiological_submission {
    *PeltColour: enum
}
entity "GrizzlyBearBiologicalSubmission" as grizzlybearbiological_submission {
    *SkullCondition: string
    *SkullLength: number
    *SkullHeight: number
    *IsEvidenceOfSexAttached: bool
}
entity "MountainGoatBiologicalSubmission" as mountaingoatbiological_submission {
    *IsHornIncluded: bool
    *IsHeadIncluded: bool
}
entity "MuleDeerBiologicalSubmission" as muledeerbiological_submission {
    *IsHornIncluded: bool
    *IsHeadIncluded: bool
}
entity "ThinhornSheepBiologicalSubmission" as thinhornsheepbiological_submission {
    *Broomed: enum
    *LengthToThirdAnnulus: number
    *PlugNumber: string
}
entity "WhiteTailtedDeerBiologicalSubmission" as whitetaileddeerbiological_submission {
    *IsHornIncluded: bool
    *IsHeadIncluded: bool
}
entity "WoodBisonBiologicalSubmission" as woodbisonbiological_submission {

}
entity "Age" as age {
    *BiologicalSubmissionId: number <<FK>>
    *Years: number
    *ConfidenceInAge: enum
}

entity "MortalityExportPermit" as mortality_export_permit {
    *Id: number <<generated>>
    --
    
}

together {
    entity "Person" as person {
        *Id: number <<generated>>
    }

    entity "ConservationOfficer" as conservation_officer {
        *BadgeNumber: string
    }

    together {
        entity "Client" as client {
            *EnvClientId: string
        }

    together {
            entity "Authorization" as authorization {
                *Id: number <<generated>>
                --
                *ClientId: number <<FK>>
                *Number: string
                *StartDate: date
                *EndDate: date
                *PosseId: number <<shadow>>
            }

            entity "HuntingLicence" as hunting_licence {

            }

            entity "HuntingPermit" as hunting_permit {

            }

            entity "PermitHuntAuthorization" as permit_hunt_authorization {

            }

            entity "SpecialGuideLicence" as special_guide_licence {

            }

            entity "TrappingLicence" as trapping_licence {

            }
    }

        entity "Seal" as seal {
            *Id: number <<generated>>
            --
            *LicenceId: number <<FK>>
            *PosseId: number <<shadow>>
        }
    }
}

entity "Violation" as violation {
    *Id: number <<generated>>
    --
    *Code: string
    *Description: string
}

entity "GameManagementArea" as game_management_area {
    *Id: number <<generated>>
    --
    *Zone: string
    *Subzone: string
    Area: string <<computed>>
}

entity "GameManagementAreaSpecies" as game_management_area_species {
    *Id: number <<generated>>
    --
    *GameManagementAreaId: number <<FK>>
    *HuntedSpeciesWithGameManagementArea: enum
}

entity "GameManagementAreaSchedule" as game_management_area_schedule {
    *Id: number <<generated>>
    --
    *GameManagementAreaSpeciesId: number <<FK>>
    *GameManagementAreaStatus: enum
    *PeriodStart: date
    *PeriodEnd: date
}

entity "GameManagementUnit" as game_management_unit {
    *Id: number <<generated>>
    --
    *Name: string
    *Number: string
    *ActiveFrom: date
    *ActiveTo: date
}

' Inheritance

mortality_report <|-- hunted_mortality_report
mortality_report <|-- human_wildlife_conflict_report
mortality_report <|-- collared_mortality_report
'mortality_report <|-- trapped_harvest_report

person <|-- client
person <|-- conservation_officer

mortality <|-- americanblackbear_mortality
mortality <|-- barrengroundcaribou_mortality
mortality <|-- canadalynx_mortality
mortality <|-- cougar_mortality
mortality <|-- coyote_mortality
mortality <|-- elk_mortality
mortality <|-- greywolf_mortality
mortality <|-- grizzlybear_mortality
mortality <|-- moose_mortality
mortality <|-- mountaingoat_mortality
mortality <|-- muledeer_mortality
mortality <|-- muskox_mortality
mortality <|-- polarbear_mortality
mortality <|-- thinhornsheep_mortality
mortality <|-- whitetaileddeer_mortality
mortality <|-- wolverine_mortality
mortality <|-- woodbison_mortality
mortality <|-- woodlandcaribou_mortality
mortality <|-- bird_mortality

biological_submission <|-up- americanblackbearbiological_submission
biological_submission <|-up- canadalynxbiological_submission
biological_submission <|-up- elkbiological_submission
biological_submission <|-up- greywolfbiological_submission
biological_submission <|-up- grizzlybearbiological_submission
biological_submission <|-up- mountaingoatbiological_submission
biological_submission <|-up- muledeerbiological_submission
biological_submission <|-up- thinhornsheepbiological_submission
biological_submission <|-up- whitetaileddeerbiological_submission
biological_submission <|-up- woodbisonbiological_submission

authorization <|-- hunting_licence
authorization <|-- hunting_permit
authorization <|-- permit_hunt_authorization
authorization <|-- special_guide_licence
authorization <|-- trapping_licence

' Relationships

hunted_mortality_report }o.right.|| game_management_area_species
hunted_mortality_report |o..|| seal
hunted_mortality_report }o..o{ violation
'trapped_harvest_report }o..|| trapping_licence

special_guide_report ||..|{ special_guide_report_hunted_mortality_report
hunted_mortality_report ||..o| special_guide_report_hunted_mortality_report
outfitter_guide_report ||..|{ outfitter_guide_report_client
client ||..o{ special_guide_report
client ||..o{ outfitter_guide_report_client
client ||..o{ hunted_mortality_report
conservation_officer ||..o{ human_wildlife_conflict_report
outfitter_guide_report ||..|{ outfitter_guide_report_hunted_mortality_report
hunted_mortality_report ||..o| outfitter_guide_report_hunted_mortality_report

mortality ||.left.|| mortality_report

americanblackbearbiological_submission |o.up.|| americanblackbear_mortality
canadalynxbiological_submission |o.up.|| canadalynx_mortality
elkbiological_submission |o.up.|| elk_mortality
greywolfbiological_submission |o.up.|| greywolf_mortality
grizzlybearbiological_submission |o.up.|| grizzlybear_mortality
mountaingoatbiological_submission |o.up.|| mountaingoat_mortality
muledeerbiological_submission |o.up.|| muledeer_mortality
thinhornsheepbiological_submission |o.up.|| thinhornsheep_mortality
whitetaileddeerbiological_submission |o.up.|| whitetaileddeer_mortality
woodbisonbiological_submission |o.up.|| woodbison_mortality

biological_submission ||..|| age

client ||..o{ authorization
hunting_licence ||..o{ seal

game_management_area ||..{ game_management_area_species
game_management_area_species ||..{ game_management_area_schedule
game_management_unit }..{ game_management_area_species

' Enums

enum "AllSpecies" as all_species {
    Uninitialized
    AmericanBeaver
    AmericanBlackBear
    AmericanMartin
    AmericanMink
    ArcticFox
    ArcticGroundSquirrel
    BarrenGroundCaribou
    BushyTailedWoodrat
    CanadaLynx
    CollaredPika
    Cougar
    Coyote
    Elk
    Ermine
    Fisher
    GreyWolf
    GrizzlyBear
    HoaryMarmot
    LeastChipmunk
    LeastWeasel
    Lemming
    LittleBrownBat
    MeadowJumpingMouse
    Moose
    MountainGoat
    MuleDeer
    Muskox
    Muskrat
    NorthAmericanDeerMouse
    NorthAmericanPorcupine
    NorthernFlyingSquirrel
    NorthernLongEaredBat
    NorthernRiverOtter
    PolarBear
    RedFox
    RedSquirrel
    Shrew
    SnowshoeHare
    ThinhornSheep
    Vole
    Wolverine
    WoodBison
    Woodchuck
    WoodlandCaribou
}

enum "BirdSpecies" as bird_species {

}

enum "WoodlandCaribouHerd" as woodland_caribou_herd {

}

enum "BarrenGroundCaribouHerd" as barren_ground_caribou_herd {

}

enum "HuntedSpecies" as hunted_species {
    Uninitialized
    AmericanBlackBear
    BarrenGroundCaribou
    Coyote
    Elk
    GreyWolf
    GrizzlyBear
    Moose
    MountainGoat
    MuleDeer
    ThinhornSheep
    Wolverine
    WoodBison
    WoodlandCaribou
}

enum "HuntedSpeciesWithGameManagementArea" as hunted_species_with_gma {
    Uninitialized
    AmericanBlackBear
    BarrenGroundCaribou
    GrizzlyBear
    Moose
    MountainGoat
    MuleDeer
    ThinhornSheep
    WoodBison
    WoodlandCaribou
}

enum "TrappedSpecies" as trapped_species {
    Uninitialized
    GreyWolf
    Wolverine
}

enum "GameManagementAreaStatus" as gma_status {
    Uninitialized
    Closed
    Open
    OpenPermitRequired
}

enum "HuntedHarvestReportStatus" as harvest_report_status {

}

enum "Sex" as sex {
    Uninitialized
    Female
    Male
    Unknown
}

enum "PregnancyStatus" as pregnancy_status {
    Uninitialized
    False
    True
    Unknown
}

enum "ThinhornSheepBodyColour" as thinhorn_sheep_body_colour {
    Uninitialized
    Dark
    Fannin
    White
}

enum "ThinhornSheepTailColour" as thinhorn_sheep_tail_colour {
    Uninitialized
    Dark
    White
}

enum "ConfidenceInAge" as confidence_in_age {
    Uninitialized
    Fair
    Good
    Poor
}

enum "OutfittingArea" as outfitting_area {

}

@enduml