@startuml new-mortality-activity-diagram
!theme materia
skinparam backgroundColor white
title Create a new mortality (harvest report)
|User|

start
repeat
    :Search for client
    by EnvClientId or
    by LastName;
    backward:Open POSSE and
    verify information;
repeat while (Client found?) is (no)
-> yes;

:Select: species;
repeat
    switch (Species?)
    case (bison, black/grizzly bear, caribou, deer, elk, goat, moose, sheep)
    fork
        :Select: seal;
    fork again
        :Select: sex;
    fork again
        :Select: GMA;
    fork again
        :Enter: landmark;
    fork again
        :Enter: coordinates;
    end fork
    switch (Species?)
    case (bison)
    fork
    if (Female?) then (yes)
        :Select: pregnant;
        note left: yes, no, unknown, n/a
    else (no)
    endif
    fork again
        :Select: wounded;
        note right: yes, no
    end fork
    case (black/grizzly bear)
    :Select: shot in conflict;
    note right: yes, no
    case (caribou, deer, elk, goat)
    case (moose)
    switch (GMA has subunit?)
    case (yes)
    :Select: subunit;
    case (no)
    endswitch
    case (sheep)
    fork
        :Select: body colour;
        note right: white, fannin, dark
    fork again
        :Select: tail colour;
        note right: white, dark
    end fork
    endswitch
    case(coyote)
    case (wolf or wolverine)
    fork
        :Select: fur seal;
        note right:Pull from data source of available furseals?
    fork again
        :Select: sex;
    fork again
        :Enter: landmark;
    fork again
        :Enter: coordinates;
    end fork
    endswitch
    :Submit form;
    |System|
    :Validate;
    if (Seal is valid? (if applicable species)) then (yes)
        if (All other required data is entered?) then (yes)
            if (All validations passed?) then (yes)
                :Set harvest report status
                to **Complete**;
            else (no)
                :Set harvest report status
                to **Complete With Violations**;
                note right: different statuses for violation types?
                :Display all violations;
            endif
        else (no)
            :Set harvest report status
            to **Waiting On Client**;
        endif
    else (no)
        :Set harvest report status
        to **Waiting On Valid Seal**;
    endif

    |User|
repeat while (Edit?) is (yes)
-> no;
if (Proceed to bio submission?) then (yes)

else (no)
    stop

    @enduml