namespace WildlifeMortalities.PosseExampleApi.Models;

public record Authorization(
    AuthorizationType Type,
    string EnvClientId,
    string Number,
    string? WildlifeActPermitConditions,
    string? SpecialGuideLicenceGuidedHunterEnvClientId,
    DateTimeOffset ActiveFromDateTime,
    DateTimeOffset ActiveToDateTime,
    DateTimeOffset LastModifiedDateTime
);

public enum AuthorizationType
{
    BigGameHuntingLicence_CanadianResident = 10,
    BigGameHuntingLicence_CanadianResidentSpecialGuided,
    BigGameHuntingLicence_NonResident,
    BigGameHuntingLicence_YukonResident,
    BigGameHuntingLicence_YukonResidentSenior,
    BigGameHuntingLicence_YukonResidentFirstNationsOrInuit,
    BigGameHuntingLicence_YukonResidentFirstNationsOrInuitSenior,
    BigGameHuntingLicence_YukonResidentTrapper,
    HuntingPermit_CaribouFortymileFall,
    HuntingPermit_CaribouFortymileSummerPeriodOne,
    HuntingPermit_CaribouFortymileSummerPeriodTwo,
    HuntingPermit_CaribouFortymileSummerPeriodThree,
    HuntingPermit_CaribouFortymileSummerPeriodFour,
    HuntingPermit_CaribouFortymileSummerPeriodFive,
    HuntingPermit_CaribouFortymileSummerPeriodSix,
    HuntingPermit_CaribouFortymileSummerPeriodSeven,
    HuntingPermit_CaribouFortymileSummerPeriodEight,
    HuntingPermit_CaribouFortymileWinter,
    HuntingPermit_CaribouHartRiver,
    HuntingPermit_CaribouNelchina,
    HuntingPermit_ElkAdaptive,
    HuntingPermit_ElkAdaptiveFirstNations,
    HuntingPermit_ElkExclusion,
    HuntingPermit_MooseThreshold,
    HuntingPermit_WoodBisonThreshold,
    HuntingSeal_AmericanBlackBear,
    HuntingSeal_Caribou,
    HuntingSeal_Deer,
    HuntingSeal_Elk,
    HuntingSeal_GrizzlyBear,
    HuntingSeal_Moose,
    HuntingSeal_MountainGoat,
    HuntingSeal_ThinhornSheep,
    HuntingSeal_WoodBison,
    OutfitterAssistantGuideLicence,
    OutfitterChiefGuideLicence,
    PhaHuntingPermit_Caribou,
    PhaHuntingPermit_Deer,
    PhaHuntingPermit_Elk,
    PhaHuntingPermit_Moose,
    PhaHuntingPermit_MountainGoat,
    PhaHuntingPermit_ThinhornSheep,
    PhaHuntingPermit_ThinhornSheepKluane,
    SmallGameHuntingLicence_CanadianResident,
    SmallGameHuntingLicence_CanadianResidentFirstNationsOrInuit,
    SmallGameHuntingLicence_NonResident,
    SmallGameHuntingLicence_NonResidentFirstNationsOrInuit,
    SmallGameHuntingLicence_YukonResident,
    SmallGameHuntingLicence_YukonResidentSenior,
    SmallGameHuntingLicence_YukonResidentFirstNationsOrInuit,
    SmallGameHuntingLicence_YukonResidentFirstNationsOrInuitSenior,
    SpecialGuideLicence,
    TrappingLicence_AssistantTrapper,
    TrappingLicence_AssistantTrapperSenior,
    TrappingLicence_ConcessionHolder,
    TrappingLicence_ConcessionHolderSenior,
    TrappingLicence_GroupConcessionAreaMember,
    TrappingLicence_GroupConcessionAreaMemberSenior,
    WildlifeActPermit
}
