using FluentValidation;
using WildlifeMortalities.Data.Entities.Reports.SingleMortality;

namespace WildlifeMortalities.App.Features.Reports;

public class IndividualHuntedMortalityReportViewModel
{
    private readonly int _reportId = Constants.EfCore.TemporaryAutoGeneratedKey;

    public IndividualHuntedMortalityReportViewModel() { }

    public IndividualHuntedMortalityReportViewModel(IndividualHuntedMortalityReport report)
    {
        HuntedActivityViewModel = new HuntedActivityViewModel(report.HuntedActivity, report);
        _reportId = report.Id;
    }

    public HuntedActivityViewModel HuntedActivityViewModel { get; set; } = new();

    public IndividualHuntedMortalityReport GetReport(int personId) =>
        new()
        {
            Id = _reportId,
            ClientId = personId,
            HuntedActivity = HuntedActivityViewModel.GetActivity()
        };
}

public class IndividualHuntedMortalityReportViewModelValidator
    : AbstractValidator<IndividualHuntedMortalityReportViewModel>
{
    public IndividualHuntedMortalityReportViewModelValidator() =>
        RuleFor(x => x.HuntedActivityViewModel)
            .SetValidator(new HuntedActivityViewModelValidator());
}
