using FluentValidation;
using WildlifeMortalities.Data.Entities;
using WildlifeMortalities.Data.Entities.Reports;
using WildlifeMortalities.Data.Entities.Reports.MultipleMortalities;

namespace WildlifeMortalities.App.Features.Reports;

public class TrappedReportViewModel : MortalityReportViewModel
{
    private readonly int _reportId = Constants.EfCore.TemporaryAutoGeneratedKey;

    public TrappedReportViewModel() { }

    public TrappedReportViewModel(TrappedMortalitiesReport report)
        : base(report)
    {
        TrappedActivityViewModels = report.TrappedActivities
            .Select(x => new TrappedActivityViewModel(x, report))
            .ToList();
        RegisteredTrappingConcession = report.RegisteredTrappingConcession;
        _reportId = report.Id;
    }

    public List<TrappedActivityViewModel> TrappedActivityViewModels { get; set; } = new();
    public RegisteredTrappingConcession? RegisteredTrappingConcession { get; set; }

    public override TrappedMortalitiesReport GetReport(int personId)
    {
        var report = new TrappedMortalitiesReport
        {
            ClientId = personId,
            TrappedActivities = TrappedActivityViewModels.ConvertAll(x => x.GetActivity()),
            RegisteredTrappingConcession = RegisteredTrappingConcession!,
            Id = _reportId,
        };

        SetReportBaseValues(report);
        return report;
    }
}

public class TrappedReportViewModelValidator
    : MortalityReportViewModelValidator<TrappedReportViewModel>
{
    public TrappedReportViewModelValidator()
    {
        RuleFor(x => x.RegisteredTrappingConcession).NotNull();
        RuleFor(x => x.TrappedActivityViewModels).NotEmpty();
    }
}
