namespace WildlifeMortalities.App;

public static class Constants
{
    public static class CascadingValues
    {
        public const string EditMode = "EditMode";
        public const string ReportType = "ReportType";
        public const string HasAttemptedFormSubmission = "HasAttemptedFormSubmission";
    }

    public static class EfCore
    {
        public const int TemporaryAutoGeneratedKey = 0;
    }

    public static class Routes
    {
        #region Report Routes
        public const string ReportDetailsPage =
            "/mortality-reports/{humanReadablePersonId}/{reportId:int}";

        public static string GetReportDetailsPageLink(string humanReadablePersonId, int reportId) =>
            $"/mortality-reports/{humanReadablePersonId}/{reportId}";

        public const string CreateReportPage = "/mortality-reports/{humanReadablePersonId}/new";

        public static string GetCreateReportPageLink(string humanReadablePersonId) =>
            $"/mortality-reports/{humanReadablePersonId}/new";

        public const string EditReportPage =
            "/mortality-reports/{humanReadablePersonId}/edit/{reportId:int}";

        public static string GetEditReportPageLink(string humanReadablePersonId, int reportId) =>
            $"/mortality-reports/{humanReadablePersonId}/edit/{reportId}";

        public const string EditDraftReportPage =
            "/mortality-reports/{humanReadablePersonId}/editdraft/{draftId:int}";

        public static string GetEditDraftReportPageLink(
            string humanReadablePersonId,
            int reportId
        ) => $"/mortality-reports/{humanReadablePersonId}/editdraft/{reportId}";
        #endregion

        #region Client Routes
        public const string ClientOverviewPage = "/clients/{envClientId}";

        public static string GetClientOverviewPageLink(string envClientId) =>
            $"reporters/clients/{envClientId}";

        public const string ClientLookupPage = "reporters/clients";

        public static string GetClientLookupPageLink() => ClientLookupPage;
        #endregion
    }
}
