// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WildlifeMortalities.Data.Legacy.Entities
{
    public partial class EnvdwEnvClient
    {
        public int? Envclientid { get; set; }
        public string Lastname { get; set; }
        public string Middleinitial { get; set; }
        public string Firstname { get; set; }
        public string Formattedname { get; set; }
        public DateTime? Birthdate { get; set; }
    }
}