// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WildlifeMortalities.Data.Legacy.Entities
{
    public partial class EnvdwEnvAuthorization
    {
        public string Harvestreportstatus { get; set; }
        public string Status { get; set; }
        public string Authorizationnumber { get; set; }
        public string Producttype { get; set; }
        public string Productgroup { get; set; }
        public string Authorizationtype { get; set; }
        public string Authorizationtypecode { get; set; }
        public string Season { get; set; }
        public string Envclientid { get; set; }
        public DateTime? Issuedate { get; set; }
        public string Issuetime { get; set; }
        public string Periodtype { get; set; }
        public DateTime? Startdate { get; set; }
        public string Starttime { get; set; }
        public DateTime? Enddate { get; set; }
        public string Endtime { get; set; }
        public string Purchasedfrom { get; set; }
        public string Issuernumber { get; set; }
        public string Issuername { get; set; }
        public string Vendorreferencenumber { get; set; }
        public decimal? Licencefee { get; set; }
        public double? Licencetaxfee { get; set; }
        public decimal? Paymentamount { get; set; }
        public string Receiptnumber { get; set; }
        public string Sealnumber { get; set; }
        public string Guided { get; set; }
        public string Guidename { get; set; }
        public string Isoutfitted { get; set; }
        public string Outfitterlist { get; set; }
        public string Conditions { get; set; }
        public DateTime? Cancellationdate { get; set; }
        public string Cancelledbyvendor { get; set; }
        public string Cancellationcreatedby { get; set; }
        public string Cancellationreason { get; set; }
        public string Cancellationcomments { get; set; }
        public DateTime? Refunddate { get; set; }
        public string Papercopyconversion { get; set; }
        public string Papercopyauthnumber { get; set; }
        public DateTime? Papercopyissuedate { get; set; }
        public DateTime? SsmaTimeStamp { get; set; }
    }
}