// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WildlifeMortalities.Data.Legacy.Entities
{
    public partial class EnvdwEnvFwHarvest
    {
        public string Reportid { get; set; }
        public DateTime? Reportdate { get; set; }
        public DateTime? Killdate { get; set; }
        public string Season { get; set; }
        public string Killtype { get; set; }
        public string Species { get; set; }
        public string Sex { get; set; }
        public double? Hrbsnumber { get; set; }
        public double? Ohenumber { get; set; }
        public string Occurrencenumber { get; set; }
        public string Clientid { get; set; }
        public string Licence { get; set; }
        public string Licencetype { get; set; }
        public string Permit { get; set; }
        public string Permittype { get; set; }
        public string Seal { get; set; }
        public double? Gma { get; set; }
        public double? Gmz { get; set; }
        public double? Gms { get; set; }
        public string Outfitterarea { get; set; }
        public string Herd { get; set; }
        public string Landmark { get; set; }
        public string Landmarkcustom { get; set; }
        public string Huntercomments { get; set; }
        public string Biologicalsubmissionstatus { get; set; }
        public string District { get; set; }
        public string Firstnations { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Recordername { get; set; }
        public int? Clientobjectid { get; set; }
        public double? Biologicalsubmissionid { get; set; }
        public int? Harvestreportobjectid { get; set; }
        public byte[] SsmaTimeStamp { get; set; }
    }
}